
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const vector_similarity_type = {
  COSINE: 'COSINE',
  L2_DISTANCE: 'L2_DISTANCE',
  INNER_PRODUCT: 'INNER_PRODUCT'
} as const

export type vector_similarity_type = (typeof vector_similarity_type)[keyof typeof vector_similarity_type]


export const ai_feature = {
  QUERY_EXPANSION: 'QUERY_EXPANSION',
  FACT_EXTRACTION: 'FACT_EXTRACTION',
  CHAPTER_SUMMARIZATION: 'CHAPTER_SUMMARIZATION'
} as const

export type ai_feature = (typeof ai_feature)[keyof typeof ai_feature]


export const book_status = {
  PARSING: 'PARSING',
  PARSED: 'PARSED',
  PROCESSING_FACTS: 'PROCESSING_FACTS',
  COMPLETED: 'COMPLETED',
  ERROR: 'ERROR'
} as const

export type book_status = (typeof book_status)[keyof typeof book_status]


export const embedding_feature_type = {
  FACT: 'FACT'
} as const

export type embedding_feature_type = (typeof embedding_feature_type)[keyof typeof embedding_feature_type]
