
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"
export type * from '../models'
export type * from './prismaNamespace'
export const Decimal = runtime.Decimal
export const ModelName = {
  book: 'book',
  chapter: 'chapter',
  fact: 'fact',
  ai_cached_embedding: 'ai_cached_embedding',
  ai_embedding_search_diagnostic: 'ai_embedding_search_diagnostic'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/**
 * Enums
 */
export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BookScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  title: 'title',
  author: 'author',
  isbn: 'isbn',
  external_id: 'external_id',
  status: 'status',
  file_path: 'file_path',
  total_pages: 'total_pages'
} as const

export type BookScalarFieldEnum = (typeof BookScalarFieldEnum)[keyof typeof BookScalarFieldEnum]


export const ChapterScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  title: 'title',
  chapter_number: 'chapter_number',
  content: 'content',
  page_start: 'page_start',
  page_end: 'page_end',
  book_id: 'book_id'
} as const

export type ChapterScalarFieldEnum = (typeof ChapterScalarFieldEnum)[keyof typeof ChapterScalarFieldEnum]


export const FactScalarFieldEnum = {
  id: 'id',
  text: 'text',
  created_at: 'created_at',
  updated_at: 'updated_at',
  embedding_id: 'embedding_id',
  chapter_id: 'chapter_id'
} as const

export type FactScalarFieldEnum = (typeof FactScalarFieldEnum)[keyof typeof FactScalarFieldEnum]


export const Ai_cached_embeddingScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  text: 'text',
  feature_type: 'feature_type'
} as const

export type Ai_cached_embeddingScalarFieldEnum = (typeof Ai_cached_embeddingScalarFieldEnum)[keyof typeof Ai_cached_embeddingScalarFieldEnum]


export const Ai_embedding_search_diagnosticScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  embedded_content_results: 'embedded_content_results',
  similarity_type: 'similarity_type',
  min_similarity: 'min_similarity',
  search_text: 'search_text',
  search_time_ms: 'search_time_ms',
  limit: 'limit',
  search_embedding_id: 'search_embedding_id'
} as const

export type Ai_embedding_search_diagnosticScalarFieldEnum = (typeof Ai_embedding_search_diagnosticScalarFieldEnum)[keyof typeof Ai_embedding_search_diagnosticScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

