
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
export const prismaVersion: PrismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

/**
 * Utility Types
 */

export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue

export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}

/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull

type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  book: 'book',
  chapter: 'chapter',
  fact: 'fact',
  ai_cached_embedding: 'ai_cached_embedding',
  ai_embedding_search_diagnostic: 'ai_embedding_search_diagnostic'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "book" | "chapter" | "fact" | "ai_cached_embedding" | "ai_embedding_search_diagnostic"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    book: {
      payload: Prisma.$bookPayload<ExtArgs>
      fields: Prisma.bookFieldRefs
      operations: {
        findUnique: {
          args: Prisma.bookFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.bookFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>
        }
        findFirst: {
          args: Prisma.bookFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.bookFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>
        }
        findMany: {
          args: Prisma.bookFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>[]
        }
        create: {
          args: Prisma.bookCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>
        }
        createMany: {
          args: Prisma.bookCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.bookCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>[]
        }
        delete: {
          args: Prisma.bookDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>
        }
        update: {
          args: Prisma.bookUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>
        }
        deleteMany: {
          args: Prisma.bookDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.bookUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.bookUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>[]
        }
        upsert: {
          args: Prisma.bookUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookPayload>
        }
        aggregate: {
          args: Prisma.BookAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBook>
        }
        groupBy: {
          args: Prisma.bookGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookGroupByOutputType>[]
        }
        count: {
          args: Prisma.bookCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookCountAggregateOutputType> | number
        }
      }
    }
    chapter: {
      payload: Prisma.$chapterPayload<ExtArgs>
      fields: Prisma.chapterFieldRefs
      operations: {
        findUnique: {
          args: Prisma.chapterFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.chapterFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>
        }
        findFirst: {
          args: Prisma.chapterFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.chapterFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>
        }
        findMany: {
          args: Prisma.chapterFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>[]
        }
        create: {
          args: Prisma.chapterCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>
        }
        createMany: {
          args: Prisma.chapterCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.chapterCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>[]
        }
        delete: {
          args: Prisma.chapterDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>
        }
        update: {
          args: Prisma.chapterUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>
        }
        deleteMany: {
          args: Prisma.chapterDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.chapterUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.chapterUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>[]
        }
        upsert: {
          args: Prisma.chapterUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$chapterPayload>
        }
        aggregate: {
          args: Prisma.ChapterAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateChapter>
        }
        groupBy: {
          args: Prisma.chapterGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ChapterGroupByOutputType>[]
        }
        count: {
          args: Prisma.chapterCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ChapterCountAggregateOutputType> | number
        }
      }
    }
    fact: {
      payload: Prisma.$factPayload<ExtArgs>
      fields: Prisma.factFieldRefs
      operations: {
        findUnique: {
          args: Prisma.factFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.factFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>
        }
        findFirst: {
          args: Prisma.factFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.factFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>
        }
        findMany: {
          args: Prisma.factFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>[]
        }
        create: {
          args: Prisma.factCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>
        }
        createMany: {
          args: Prisma.factCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.factCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>[]
        }
        delete: {
          args: Prisma.factDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>
        }
        update: {
          args: Prisma.factUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>
        }
        deleteMany: {
          args: Prisma.factDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.factUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.factUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>[]
        }
        upsert: {
          args: Prisma.factUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$factPayload>
        }
        aggregate: {
          args: Prisma.FactAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFact>
        }
        groupBy: {
          args: Prisma.factGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FactGroupByOutputType>[]
        }
        count: {
          args: Prisma.factCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FactCountAggregateOutputType> | number
        }
      }
    }
    ai_cached_embedding: {
      payload: Prisma.$ai_cached_embeddingPayload<ExtArgs>
      fields: Prisma.ai_cached_embeddingFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ai_cached_embeddingFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ai_cached_embeddingFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload>
        }
        findFirst: {
          args: Prisma.ai_cached_embeddingFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ai_cached_embeddingFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload>
        }
        findMany: {
          args: Prisma.ai_cached_embeddingFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload>[]
        }
        delete: {
          args: Prisma.ai_cached_embeddingDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload>
        }
        update: {
          args: Prisma.ai_cached_embeddingUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload>
        }
        deleteMany: {
          args: Prisma.ai_cached_embeddingDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ai_cached_embeddingUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ai_cached_embeddingUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_cached_embeddingPayload>[]
        }
        aggregate: {
          args: Prisma.Ai_cached_embeddingAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAi_cached_embedding>
        }
        groupBy: {
          args: Prisma.ai_cached_embeddingGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Ai_cached_embeddingGroupByOutputType>[]
        }
        count: {
          args: Prisma.ai_cached_embeddingCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Ai_cached_embeddingCountAggregateOutputType> | number
        }
      }
    }
    ai_embedding_search_diagnostic: {
      payload: Prisma.$ai_embedding_search_diagnosticPayload<ExtArgs>
      fields: Prisma.ai_embedding_search_diagnosticFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ai_embedding_search_diagnosticFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ai_embedding_search_diagnosticFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>
        }
        findFirst: {
          args: Prisma.ai_embedding_search_diagnosticFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ai_embedding_search_diagnosticFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>
        }
        findMany: {
          args: Prisma.ai_embedding_search_diagnosticFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>[]
        }
        create: {
          args: Prisma.ai_embedding_search_diagnosticCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>
        }
        createMany: {
          args: Prisma.ai_embedding_search_diagnosticCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ai_embedding_search_diagnosticCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>[]
        }
        delete: {
          args: Prisma.ai_embedding_search_diagnosticDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>
        }
        update: {
          args: Prisma.ai_embedding_search_diagnosticUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>
        }
        deleteMany: {
          args: Prisma.ai_embedding_search_diagnosticDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ai_embedding_search_diagnosticUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ai_embedding_search_diagnosticUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>[]
        }
        upsert: {
          args: Prisma.ai_embedding_search_diagnosticUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ai_embedding_search_diagnosticPayload>
        }
        aggregate: {
          args: Prisma.Ai_embedding_search_diagnosticAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAi_embedding_search_diagnostic>
        }
        groupBy: {
          args: Prisma.ai_embedding_search_diagnosticGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Ai_embedding_search_diagnosticGroupByOutputType>[]
        }
        count: {
          args: Prisma.ai_embedding_search_diagnosticCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Ai_embedding_search_diagnosticCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BookScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  title: 'title',
  author: 'author',
  isbn: 'isbn',
  external_id: 'external_id',
  status: 'status',
  file_path: 'file_path',
  total_pages: 'total_pages'
} as const

export type BookScalarFieldEnum = (typeof BookScalarFieldEnum)[keyof typeof BookScalarFieldEnum]


export const ChapterScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  title: 'title',
  chapter_number: 'chapter_number',
  content: 'content',
  page_start: 'page_start',
  page_end: 'page_end',
  book_id: 'book_id'
} as const

export type ChapterScalarFieldEnum = (typeof ChapterScalarFieldEnum)[keyof typeof ChapterScalarFieldEnum]


export const FactScalarFieldEnum = {
  id: 'id',
  text: 'text',
  created_at: 'created_at',
  updated_at: 'updated_at',
  embedding_id: 'embedding_id',
  chapter_id: 'chapter_id'
} as const

export type FactScalarFieldEnum = (typeof FactScalarFieldEnum)[keyof typeof FactScalarFieldEnum]


export const Ai_cached_embeddingScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  text: 'text',
  feature_type: 'feature_type'
} as const

export type Ai_cached_embeddingScalarFieldEnum = (typeof Ai_cached_embeddingScalarFieldEnum)[keyof typeof Ai_cached_embeddingScalarFieldEnum]


export const Ai_embedding_search_diagnosticScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  embedded_content_results: 'embedded_content_results',
  similarity_type: 'similarity_type',
  min_similarity: 'min_similarity',
  search_text: 'search_text',
  search_time_ms: 'search_time_ms',
  limit: 'limit',
  search_embedding_id: 'search_embedding_id'
} as const

export type Ai_embedding_search_diagnosticScalarFieldEnum = (typeof Ai_embedding_search_diagnosticScalarFieldEnum)[keyof typeof Ai_embedding_search_diagnosticScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'book_status'
 */
export type Enumbook_statusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'book_status'>
    


/**
 * Reference to a field of type 'book_status[]'
 */
export type ListEnumbook_statusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'book_status[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'embedding_feature_type[]'
 */
export type ListEnumembedding_feature_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'embedding_feature_type[]'>
    


/**
 * Reference to a field of type 'embedding_feature_type'
 */
export type Enumembedding_feature_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'embedding_feature_type'>
    


/**
 * Reference to a field of type 'vector_similarity_type'
 */
export type Enumvector_similarity_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'vector_similarity_type'>
    


/**
 * Reference to a field of type 'vector_similarity_type[]'
 */
export type ListEnumvector_similarity_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'vector_similarity_type[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  book?: Prisma.bookOmit
  chapter?: Prisma.chapterOmit
  fact?: Prisma.factOmit
  ai_cached_embedding?: Prisma.ai_cached_embeddingOmit
  ai_embedding_search_diagnostic?: Prisma.ai_embedding_search_diagnosticOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

